version: '3'

services:
  db:
    image: mysql:latest
    container_name: pure_db
    environment:
      DB_HOST: db
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_password
      MYSQL_ROOT_PASSWORD: sample123   
    restart: always 
    ports:
      - 3306:3306
    

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pure_app
    environment:
      DB_HOST: db
      DB_NAME: sample_db
      DB_USER: sample_user
      DB_PASSWORD: sample_password
    ports:
      - 8001:8000
    depends_on:
      - db
    links:
      - db
